"""Create table

Revision ID: 310e5ce04adf
Revises: 
Create Date: 2025-02-28 21:37:17.732296

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310e5ce04adf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('display',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('previous_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_frequency', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_display_name'), 'display', ['name'], unique=False)
    op.create_table('update',
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['display_id'], ['display.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update')
    op.drop_index(op.f('ix_display_name'), table_name='display')
    op.drop_table('display')
    # ### end Alembic commands ###
