"""Add full refresh frequency

Revision ID: cf969f1ba7c1
Revises: 310e5ce04adf
Create Date: 2025-03-02 10:40:32.199674

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf969f1ba7c1'
down_revision: Union[str, None] = '310e5ce04adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('display', sa.Column('full_refresh_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('display', 'full_refresh_frequency')
    # ### end Alembic commands ###
